using System;
using System.Collections.Generic;
//add this when defining attributes to validate the forms
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
//add this o be able to use class CheeseType
using CheeseMVC.Models;
//add using statement for SelectListItems
using Microsoft.AspNetCore.Mvc.Rendering;

//use for data in the form and form processing (shows up in the view)
namespace CheeseMVC.ViewModels
{
    public class AddCheeseViewModel
    {
        //need to gather multiple types of information to add a new cheese object
        //add attribute to property to validate form
        [Required] //validates name property to ensure name is input in form
        //ensure display models are displayed in the view
        //will show up in the form title saying "Cheese Name" rather than just "Name"
        //other types of validation can be found in microsoft documentation
        [Display(Name = "Cheese Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "You must give your cheese a description.")]
        public string Description { get; set; }
        //add property to represent cheese type user is going to set when they create the form
        //stores type of cheese that the user has selected
        public CheeseType Type { get; set; }
        [Range(1,5)]
        public int Rating { get; set; }

        //create list of cheese types for user to select
        public List<SelectListItem> CheeseTypes { get; set; }

        //create select list items to represent different cheese types (one ay is through a constructor of the class)
        public AddCheeseViewModel()
        {
            //initialize empty list
            CheeseTypes = new List<SelectListItem>();

            //add types of cheese
            //html generated by each selectlistitem: <option value="0">Hard</option> (number and option corresponds
            //to different enum value and name in cheesetype class
            CheeseTypes.Add(new SelectListItem
            {
                Value = ((int) CheeseType.Hard).ToString(),
                Text = CheeseType.Hard.ToString()
            });

            CheeseTypes.Add(new SelectListItem
            {
                Value = ((int)CheeseType.Soft).ToString(),
                Text = CheeseType.Soft.ToString()
            });

            CheeseTypes.Add(new SelectListItem
            {
                Value = ((int)CheeseType.Fake).ToString(),
                Text = CheeseType.Fake.ToString()
            });
        }
    }
}
